fix #33 Project update to 2023.02.xx
geosolutions-it/MapStore-C179 pull request #34
Opened 2023-11-21 08:50 UTC by MV88

fix #33 Project update to 2023.02.xx

2023-11-28 09:47 UTC, offtherailz requested changes
I think it we are almost there. 
- [x] See comments inline.
- [x] Please document on the readme how to run locally for future tests, development and update, I was not able to do it running standard commands. 
- [x] Please document also LDAP custom variables, if any. 
- [x] package-lock.json is old. What if we commit an update for it?
- [ ] test properly
- [ ] Make sure to apply upgrades also on installation (compile a list, if I missed something), see details below.

### Documentation notes

Readme file I think is enough to  document how to run locally and how to configure (when not standard LDAP configuration, in case link the onine documentation).

**also** update node version indication on readme.

### Testing notes

Make sure to have tested this project widely (I'll not do, and I wasn't able to do it because of reasons above).
Especially things that had to be ported manually during upgrade, like:
- embedded templates for all content to be working
- ldap configuration
- printing

### Deploy notes

During installation, take also into account to:
- create the missing categories on installation (PERMALINK, USERSESSION, TEMPLATE)
- database schema probably changed. meke sure to update `geostore-datasource-ovr.properties` to automatically apply changes, or to apply the proper changes to the schema manually to the existing geostore.
```
# Automatic create-update database mode
geostoreEntityManagerFactory.jpaPropertyMap[hibernate.hbm2ddl.auto]=update

2023-11-28 09:47 UTC, offtherailz commented on export.sh
> +export LDAP_URL="ldap://this.will.not.work:389/dc=xxxxx,dc=xxxxx,dc=xxxxx"
I think this is a script for testing. Document it or drop it.

2023-11-28 09:47 UTC, offtherailz commented on web/src/main/resources/mapstore.properties
> +extensions.registry=extensions.json
Is this really needed for a project? I don't remember this ... Where did you find this change to apply?

2023-11-28 09:47 UTC, offtherailz commented on web/src/main/resources/sample_categories.xml
> +    </Category>
These will need to be created if the database already exists.

2023-11-28 09:47 UTC, offtherailz commented on web/src/main/webapp/WEB-INF/classes/geostore-spring-security.xml
> +                                                <constructor-arg index="1" value="(&amp;(objectCategory=${LDAP_USER_SEARCH_CATEGORY})(|#LDAP_GROUPS)(sAMAccountName={0}))" />
has this been already tested ?

2023-11-30 11:39 UTC, MV88 commented on web/src/main/resources/sample_categories.xml
> +    </Category>
yes, it's a devop task

2023-11-30 11:40 UTC, MV88 commented on web/src/main/webapp/WEB-INF/classes/geostore-spring-security.xml
> +                                                <constructor-arg index="1" value="(&amp;(objectCategory=${LDAP_USER_SEARCH_CATEGORY})(|#LDAP_GROUPS)(sAMAccountName={0}))" />
this was the original implementation  and i suppose it was tested back in the days. we will test it after deploy  update i guess

2023-11-30 11:42 UTC, MV88 commented on export.sh
> +export LDAP_URL="ldap://this.will.not.work:389/dc=xxxxx,dc=xxxxx,dc=xxxxx"
i'll document it and i'll include in start commands

2023-12-06 17:24 UTC, offtherailz requested changes
I updated the README with some testing hints. They are not optimal but at least we can try it with a mock LDAP.  For the future we can improve them.

- [x] There are a few differences in theme. Take a look if you can uniform them with the standard theme. I don't see in fact a lot of customization to be maintained. Isn't it?
![image](https://github.com/geosolutions-it/MapStore-C179/assets/1279510/fccfbdd9-d63a-4298-b926-96402578bb48)
- [ ] Need to document the properties. I asked @randomorder to provide a sample (without credentials) of the variables to give an Idea of the final result. 
- [ ] I still see `mapstore.properties` set as I said here, but not answer here. https://github.com/geosolutions-it/MapStore-C179/pull/34#discussion_r1407436008
- [ ] How can we make sure that the changes will be applied on deploy (*Deploy notes* [here](https://github.com/geosolutions-it/MapStore-C179/pull/34#pullrequestreview-1752367895) ). Should we write an update note @randomorder ?

2023-12-15 10:22 UTC, MV88 commented
>  There are a few differences in theme. Take a look if you can uniform them with the standard theme. I don't see in fact a lot of customization to be maintained. Isn't it?

it appears that some customized variables in the old version of the project were not used or the theme structure was different, 
but now i have aligned these 
@ms2-color-disabled: #5C9FB4;
@ms2-color-text-disabled: #ffffff;
to become 
@ms-disabled-bg: #eee;
@ms-disabled-color: #999;

the fix will arrive in a new commit

> I still see mapstore.properties set as I said here, but not answer here. https://github.com/geosolutions-it/MapStore-C179/pull/34#discussion_r1407436008

I have just aligned the properties file as listed in the checklist of migration guidelines, do i have to avoid to do this change?

2023-12-19 13:13 UTC, offtherailz requested changes
waiting for extension.json to be checked.
Rest of the notes have to be passed to @randomorder

2023-12-19 13:58 UTC, tdipisa commented
> waiting for extension.json to be checked. Rest of the notes have to be passed to @randomorder

@MV88 after merging this PR a new issues for the deployment should be created for @randomorder by reporting all relevant activities to take into account point by point.

2023-12-19 14:52 UTC, offtherailz approved these changes

2023-12-19 15:40 UTC, tdipisa requested changes
@MV88 you may want to check compile failures before merging this PR.

2023-12-20 14:13 UTC, tdipisa commented
> > waiting for extension.json to be checked. Rest of the notes have to be passed to @randomorder
> 
> @MV88 after merging this PR a new issues for the deployment should be created for @randomorder by reporting all relevant activities to take into account point by point.

That's the related issue @EddyCatt @randomorder 

https://github.com/geosolutions-it/MapStore-C179/issues/35

2023-12-20 14:14 UTC, tdipisa approved these changes

2023-12-20 14:18 UTC, merged