#50: Project update to MS v2024.01.02
geosolutions-it/MapStore-C179 pull request #51
Opened 2024-08-07 06:57 UTC by dsuren1

## Description
This PR updates the MS submodule version to v2024.01.02 along with
- print scale in `config.yaml`
- version

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Enhancement

## Issue

**What is the current behavior?**
- #50 

**What is the new behavior?**
MS submodule updated to v2024.01.02 and other related migrations in the project

### DB Changes
Follow the migration details with respect to DB/schema changes:

-  Resource metadata to include information about resource creator/editor and **advertised/unadvertised** info

   In detail migration information is available [here](https://docs.mapstore.geosolutionsgroup.com/en/v2024.01.00/developer-guide/mapstore-migration-guide/#database-update) 

    **POSTGRESQL** 
     - https://github.com/geosolutions-it/geostore/blob/master/doc/sql/migration/postgresql/postgresql-migration-from-v.2.0.0-to-v2.1.0.sql
     
    **ORACLE**
    - https://github.com/geosolutions-it/geostore/blob/master/doc/sql/migration/oracle/oracle-migration-from-v.2.0.0-to-v2.1.0.sql
    
    **H2**
    - https://github.com/geosolutions-it/geostore/blob/master/doc/sql/migration/h2/h2-migration-from-v.2.0.0-to-v2.1.0.sql

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2024-08-12 14:07 UTC, MV88 requested changes

2024-08-12 14:07 UTC, MV88 commented on configs/localConfig.json
> -      "https://gs-stable.geo-solutions.it:443/geoserver"
i'm not sure we have to spread these in our clients projects

2024-08-12 14:07 UTC, MV88 commented on web/pom.xml
> +    <jaxws-api.version>2.3.1</jaxws-api.version>
reuse these version values in the version below

2024-08-12 15:56 UTC, MV88 requested changes
please restore use cors entries.

we might keep them

2024-08-13 10:50 UTC, MV88 approved these changes

2024-08-19 07:48 UTC, tdipisa commented
@EddyCatt I will wait for your green light before merging this PR at the beginning of September as agreed.

2024-10-11 15:50 UTC, merged